### ISSUE TITLE
°C as Unit for Dimmer and Hue

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.devices#119]
I created some lamps from type 'hue'. 
The attributes Dimmer and Hue have a unit of "Degree Celsius".
![hue](https://user-images.githubusercontent.com/66745270/142936401-99e02264-8b1c-44b4-ac65-e0053b7d615b.JPG)

**Comment by Apollon77** [comment]
But then this feels like an error from the hue adapter or is the unit not defined from there?

**Comment by ElRedef** [comment]
The devices adapter adds the unit:

Created from adapter:

`{
  "_id": "alias.0.Flur.Rot.DIMMER",
  "native": {},
  "type": "state",
  "common": {
    "alias": {
      "id": "hue.0.Rot.level"
    },
    "name": "DIMMER",
    "role": "level.dimmer",
    "write": true,
    "type": "number",
    "unit": "°C"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1637694498696,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

original:

`
{
  "_id": "hue.0.Rot.level",
  "type": "state",
  "common": {
    "name": "Rot.level",
    "read": true,
    "write": true,
    "type": "number",
    "role": "level.dimmer",
    "min": 0,
    "max": 100,
    "def": 0
  },
  "native": {
    "id": "1"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1637090770481,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`

**Comment by Apollon77** [comment]
The  you need to remove the unit from your created alias object ... this is simply wrong  ... so you need to configure it correctly
