### ISSUE TITLE
Homematic - not all datapoints listed

### ISSUE THREAD

**Issue by SvenTej** [ioBroker/ioBroker.devices#122]
Hey there,
today I installed the most recent version of the adapter.

I use a Homematic CU based on the most recent raspberrymatic.

Basically all devices are present in the HM-RPC section in the objectlist.

In the "native devices list" some of them are missing:
- remote control is missing completely (HM-RC-Dis-H-x-EU) 
- the window contacts (HmIP-SRH) are only showed as information device

Is this the planned behaviour ?
I would expect that a remote control and also the window contacts should be visible.

Greets from Stuttgart
Sven

**Comment by Apollon77** [comment]
Please provide screenshots of the availabel states and objects from these devices with their roles (maybe screenshots from "obejcts" tab

**Comment by Feuer-sturm** [comment]
Not fixed yet
