### ISSUE TITLE
Alias Kamera.FILE has no target

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.devices#135]
**Describe the bug**  
During creation of the "Kamera" device the warning in the log will be shown. A target for "File" is not available.

**To Reproduce**  
1. Create device "Kamera"

**Expected behavior**  
No warning in the log

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/147862963-2bb37a25-2751-4d8b-a3d7-e2e5852b681e.png)

```
2022-01-02 01:08:15.406 - warn: javascript.0 (348) Alias alias.0.testobjekte.Kamera.FILE has no target 12
2022-01-02 01:08:15.409 - warn: javascript.0 (348) Could not add alias subscription: Alias alias.0.testobjekte.Kamera.FILE has no target 12
```

**Versions:**  
- Adapter version: 1.0.9
- JS-Controller version: 3.3.22
- Node version: 14.18.1

**Comment by Wildbill-Z** [comment]
Wird wohl [dasselbe Thema](https://github.com/ioBroker/ioBroker.devices/issues/127) sein.
Gruss, Jürgen
