### ISSUE TITLE
Alias Jalousien.SET has no target

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.devices#136]
**Describe the bug**  
 During creation of the "Jalousien" device the warning in the log will be shown. A target for "Set" is not available.

**To Reproduce**  
1. Create device "Jalousien"

**Expected behavior**  
 No warning in the log

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/147863183-8944352a-2cd1-4fd9-8936-186ca659278b.png)

```
2022-01-02 01:06:56.806 - warn: javascript.0 (348) Alias alias.0.testobjekte.Jalousien.SET has no target 12
2022-01-02 01:06:56.810 - warn: javascript.0 (348) Could not add alias subscription: Alias alias.0.testobjekte.Jalousien.SET has no target 12
```

**Versions:**  
- Adapter version: 1.0.9
- JS-Controller version: 3.3.22
- Node version: 14.18.1

**Comment by Wildbill-Z** [comment]
Wird wohl [dasselbe Thema](https://github.com/ioBroker/ioBroker.devices/issues/127) sein.
Gruss, Jürgen
