### ISSUE TITLE
Temperatursensor: Luftfeuchtigkeit wird in Google-Assistant nicht angezeigt

### ISSUE THREAD

**Issue by petterpet** [ioBroker/ioBroker.devices#158]
Ich habe Temperatursensoren als Gerätetyp "Temperatur" angelegt und entsprechend verknüpft. Diese übermitteln Temperatur und Luftfeuchtigkeit:
![image](https://user-images.githubusercontent.com/41487271/162992938-ccb7f617-bf7f-4bbe-9e76-577060028e18.png)

Die Google-Geräte im iot-Adapter erkennen nur die Temperatur:
![image](https://user-images.githubusercontent.com/41487271/162993125-b4cb4a2a-abf3-425f-959c-749f60e239b5.png)
Dementsprechend wird die Luftfeuchtigkeit nicht an den Google-Assistant übermittelt.
Ich kann den State "SECOND" auch nicht manuell hinzufügen, nur als neues Gerät.

Lege ich den Sensor als "Thermostat" an werden beide Werte übermittelt. Nachteil hieran ist, dass sich die Temperatur dann auch mit Google verändern lässt, was ja logischerweise nicht funktioniert.
![image](https://user-images.githubusercontent.com/41487271/162994083-c35175d5-4207-4475-b96d-b35d8f37e38d.png)

Bitte den Typ "Temperatur" so anpassen, dass mehr als ein State erkannt wird.

**Versions:**  
 - Adapter version: 1.0.10 (iot: 1.8.24)
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: Ubuntu Server

**Comment by Apollon77** [comment]
Wie sehen denn die Objekte in beiden Fällen aus? Vor allem was Datentyp und rolle angeht? Kann sein das der ndere level.humidity hat?

**Comment by petterpet** [comment]
Hier die Objekte:
![image](https://user-images.githubusercontent.com/41487271/163050326-2efb85dd-c665-4c79-b103-b3139c82890a.png)
Oben "Temperatur" und darunter "Thermostat" je mit dem gleichen physikalischen Gerät.

So sieht das im Devices-Adapter aus:
![image](https://user-images.githubusercontent.com/41487271/163050472-8dde481c-8bd6-4d2e-a4e5-394162a2c765.png)

In beiden Fällen ist die Rolle `value.humidity`.
Der Datentyp ist `number`:
![image](https://user-images.githubusercontent.com/41487271/163051011-9a6d003a-771a-48b6-894e-cb93b7dc6586.png)
Hier unterscheidet sich lediglich der Name von _HUMIDITY_ zu _SECOND_.


------------
Das Testgerät wird von Google so nur lesend erkannt (wenn bei SET kein Datenpunkt verknüpft ist). Dieser ist leider trotzdem da, da er Pflicht ist.

**Comment by petterpet** [comment]
Update:
Der Fehler tritt nur auf wenn es mehrere Geräte mit dem gleichen _intelligenten Namen_ gibt.

Ich hatte in drei Räumen je ein Gerät mit dem Namen "Temperatur". Hänge ich an den Namen je etwas an (z. B. den Raumnamen) werden sowohl Temperatur als auch Luftfeuchtigkeit übermittelt.

**Comment by Apollon77** [comment]
Ok, dann ist es also eher ein iot issue?

**Comment by petterpet** [comment]
Den Gedanke hatte ich mittlerweile auch schon nach längerem ausprobieren.

**Comment by Apollon77** [comment]
Ok, machste dann da bitte ein issue und am besten iot in Debug log starten, vllt sieht man dann im Log was
