### ISSUE TITLE
can't install adapter devices

### ISSUE THREAD

**Issue by watcherkb** [ioBroker/ioBroker.devices#16]
Tried to install this adapter. Devices tab is not showing. Debug output shows:

`$ ./iobroker url "https://github.com/ioBroker/ioBroker.devices/tarball/master" devices --debug
install https://github.com/ioBroker/ioBroker.devices/tarball/master
NPM version: 6.13.4
npm install https://github.com/ioBroker/ioBroker.devices/tarball/master --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.devices@0.3.2updated 1 package in 7.352s
18 packages are looking for funding  run `npm fund` for details
upload [19] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/vendor/socket.io.js vendor/socket.io.js application/javascript
upload [18] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/tab.html tab.html text/html
upload [17] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/media/copy-content.6fe0b363.svg static/media/copy-content.6fe0b363.svg image/svg+xml
upload [16] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/runtime-main.9e8db918.js.map static/js/runtime-main.9e8db918.js.map application/json
upload [15] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/runtime-main.9e8db918.js static/js/runtime-main.9e8db918.js application/javascript
upload [14] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/main.205ea7f4.chunk.js.map static/js/main.205ea7f4.chunk.js.map application/json
upload [13] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/main.205ea7f4.chunk.js static/js/main.205ea7f4.chunk.js application/javascript
upload [12] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.0cabee84.chunk.js.map static/js/2.0cabee84.chunk.js.map application/json
upload [11] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.0cabee84.chunk.js.LICENSE.txt static/js/2.0cabee84.chunk.js.LICENSE.txt text/plain
upload [10] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.0cabee84.chunk.js static/js/2.0cabee84.chunk.js application/javascript
upload [9] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/css/2.ac70b322.chunk.css.map static/css/2.ac70b322.chunk.css.map application/json
upload [8] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/css/2.ac70b322.chunk.css static/css/2.ac70b322.chunk.css text/css
upload [7] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/service-worker.js service-worker.js application/javascript
upload [6] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/precache-manifest.699b7fe26982f5bd82fb737e8cd7fed3.js precache-manifest.699b7fe26982f5bd82fb737e8cd7fed3.js application/javascript
upload [5] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/manifest.json manifest.json application/json
upload [4] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/index_m.html index_m.html text/html
upload [3] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/index.html index.html text/html
upload [2] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [1] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/devices.png devices.png image/png
upload [0] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/asset-manifest.json asset-manifest.json application/json
INFO: Directory "/opt/iobroker/node_modules/iobroker.devices/www" was not found! Nothing was uploaded or deleted.
process exited with code 0`

**Versions:**  
Betriebssystem linux
os linux
Architektur x64
CPUs 2
Geschwindigkeit 3504 MHz
Modell Common KVM processor
RAM 3.82 GB
System Betriebszeit 00:38:58
Node.js v10.18.1 (Es gibt eine neuere Version: v10.19.0)
NPM 6.13.4

**Comment by watcherkb** [comment]
after install 0.3.1, Devices (in german Geräte) was shown

**Comment by Apollon77** [comment]
so can be closed?
