### ISSUE TITLE
Device list empty

### ISSUE THREAD

**Issue by botswanabub** [ioBroker/ioBroker.devices#163]
tried to use device adapter for lovelace UI. but device list add no devices automatical.
manual added alias will be detected.

not really sure if it's a bug, or if I'm doing something wrong.

**Screenshots & Logfiles**  
Error in debug: "Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null)."
<img width="1257" alt="iobroker-devices-debug" src="https://user-images.githubusercontent.com/56712501/166135356-3a2ba6bb-8a81-4a4e-83c0-a59565aa1c0b.png">

**Versions:**  
 - Adapter version: 1.0.10
 - JS-Controller version: 4.0.23
 - Node version: v14.19.1
 - Operating system: linux

**Comment by Apollon77** [comment]
Ok, there is no error that is relevant here (ignore the sentry one). So what exactly is your expectation and whats missing?

The devices adapter will show devices where are are some. Else yfind anything in "native devices" and can "convert them to devices or create new devices

**Comment by botswanabub** [comment]
Hi. thanks for reply. Primary I installed this adapter for testing the lovelace UI -> figured out it's not necessarry.
So what I expected was a list of my devices like shelly/zigbee/wled filled automatical. But therefore I wrote perhaps I did something wrong. Sorry for trouble.

**Comment by Apollon77** [comment]
This is not that easy ... so open the "Native devices" folder and you should see exactly that ... but in fact it is a "guessing of the devices adapter" because adapters structure their devices differently ... The Device adapter allows you to bring it to a general level by converting these netive devices to "same structured virtual devices"

**Comment by Apollon77** [comment]
But yes would need some roe descriptions it seems

**Comment by botswanabub** [comment]
exacly that folder is empty, that's why my confusion. but finally I have to study that adapter more I think. At moment not that important thing.
![Screenshot 2022-05-03 at 11-52-23 devices - iobroker](https://user-images.githubusercontent.com/56712501/166434535-9c8448c6-1320-4b32-9226-66815162ae95.png)

**Comment by Apollon77** [comment]
Then the reason is that you most likely tat you do not use enums for "rooms" and "functions" because the devices adapter only search for devices with thsi right now ...
