### ISSUE TITLE
Multiple sockets alias

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.devices#17]
Hi .. first steps with this adapter .. is it possible to use one alias for multiple sockets .. like can I simply make copies and change the socket? And what is the "Actual" line in the settings?

**Comment by Apollon77** [comment]
What docker you mean?

**Comment by daniel-lo** [comment]
Oh .. I don't mean IP sockets .. but electrical ones ;-)

![2020-03-01_072442 io](https://user-images.githubusercontent.com/4311558/75620814-c44b3180-5b8d-11ea-9f96-f67b68c400f6.png)

**Comment by Apollon77** [comment]
Aaahh now I see. No alias at the moment is a 1:1 relation

**Comment by daniel-lo** [comment]
ok .. thanks .. what about this actual line?

**Comment by Apollon77** [comment]
In fact rjisnisnseparationnbewtween „the value to set“ (SET) and the current enabled/disabled value. If it is represented by the same state for your device set the same for both

**Comment by daniel-lo** [comment]
hmm .. haven't got it yet ..  is the one to SET the state and the other one to figure out which state it currently has?

**Comment by Apollon77** [comment]
No,

SET is the stae you use to SET a new value for the device. So it is kind of "write only". reading it might not return the curret value but the last "set" one

ACTUAL is the current value of the device state which was reported by the device

The devices adapter tries to standardize the structure of devices to be easier used e.g. by visualization adapters

**Comment by daniel-lo** [comment]
wonderful .. exactly what I had meant to say :-)
