### ISSUE TITLE
Frage: Runden auf 1 Stelle hinter Komma

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.devices#180]
**Describe the bug**  
Ich möchte einen Wetrt auf eine Stelle runden.
Was muss ich hier eingeben?
In JavaScript würde man wohl val.toFixed(1) angeben.
![grafik](https://user-images.githubusercontent.com/47006370/190582175-288739d6-d1bd-4bb2-8d35-1f2967bc5bc7.png)

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: up to date
 - JS-Controller version: up to date
 - Node version: up to date
 - Operating system: debian

**Additional context**

**Comment by Apollon77** [comment]
Usage questions are better in Forum, but in fact near to right ...
if you do "toFixed" you will get a String as result ... so if you still need a number you need to use parseFloat areound that again ... or you round differently

So in fact "parseFloat(val.toFixed(1))" is one option, "(val*10)/10" is the maybe more performant option
