### ISSUE TITLE
Wo finde ich eine Dokumentation?

### ISSUE THREAD

**Issue by h1-frankfurt** [ioBroker/ioBroker.devices#184]
Man sucht sich tot und findel Keine Dokumentation. Scheint ja wirklich hilfreich su sein der Adapter.
mfg h1

**Comment by Apollon77** [comment]
Hm ... Und ewas genau erwartest Du von der Erstellung eines solchen Issues? Zu Fragen zur Nutzung wäre das Forum hilfreich, da gibts Posts dazu ...

**Comment by h1-frankfurt** [comment]
Danke für die schnelle Antwort. Es ist schon bestimmt 30 Jahre her da war ich mal Anwendungsenwickler damals galt der Grundsatz, eine Software ist nur so gut wie ihre Dokumentation. Wie soll man sie sonst richtig nutzen. Welches Forum bitte habe keinen Link gefunden. Dankeschön.

**Comment by Apollon77** [comment]
https://forum.iobroker.net
