### ISSUE TITLE
Devices tab now selectable

### ISSUE THREAD

**Issue by HanSolo72** [ioBroker/ioBroker.devices#19]
Hi, I can't activate the devices tab. As you can see, it is installed:
https://i.imgur.com/TaBuaEY.png

**Comment by Apollon77** [comment]
An what happens if you selection it?
Is there any error in the web error console ( developer tools)

**Comment by HanSolo72** [comment]
Ok, after I deleted an installed the adapter again and I deselected one of the tabs, magically "Geräte" (which is German for Devices) appeared to select. It works now.
