### ISSUE TITLE
icon is not get from right url

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.devices#2]
If object defined icon in there state, device adapter will get the icon from the url.
But it seems the URL is not right

For example:
![image](https://user-images.githubusercontent.com/4982108/64440435-89949f00-d0fe-11e9-9169-54d2879121fc.png)
The icon url in device adatper is `https://iob.xxxx.xxxx/adapter/devices/adapter/mihome/icons/curtain.png`
But the right url is 
`https://iob.xxxx.xxxx/adapter/mihome/icons/curtain.png`

Just mark this issue, no push

**Comment by GermanBluefox** [comment]
Should work now

**Comment by SchumyHao** [comment]
Fixed. Thank you
