### ISSUE TITLE
zustand in zustand übertragen

### ISSUE THREAD

**Issue by vonCartman** [ioBroker/ioBroker.devices#208]
Hallo Zusammen,

besteht die möglichkeiten das innerhalb von einen Gerät werden zustande übetragen.
Gemeint ist: zustand true/false aus einen objekt (shelly.0.SHSW-1#3083988C0072#1.Relay0.Switch) in anderen zustand (0_userdata.0.TestBolean) zu schreiben ?

[http://www.smarthome.diewollners.de/2022_11_27_01_33_37.png]

**Comment by Garfonso** [comment]
Warum willst du das tun? 

Sag doch mal, was du eigentlich erreichen willst, vielleicht gibt es dafür schon eine einfachere Lösung. ( https://de.wikipedia.org/wiki/XY-Problem )

**Comment by Apollon77** [comment]
@vonCartman Also das geht entweder mit einem einfachen Javascriptchen . ist ein einzeler dort.

Aber ja die interessante Frage ist was genau du vorhast

**Comment by vonCartman** [comment]
@Garfonso @Apollon77 

Ausgangslage:
 * Bestandhaus mit KNX bus nachgerustet
 * Fasst alle Fenster an Binnarenaktor angeschloßen
 * 1 fenster ohne KNX Fensterkontakt (Fliesen, wollte nicht zersören) --> Notfalllösung Shelly Fenster kontakt

Problem:
Status von shelly fensterkontakt True/Falsch an KNX adapter übertragen

Lösung:
1) klar, JS/Blockly mit trigger an ShellyObjekt
2) ohne Lösung 1, der Adapter Device/Alias übeträgt die werte inerhalb

Ich hoffe habe ich gut beschreiben. 
Bei unklarheiten weiter nachfragfen.

Danke im Vorfeld
