### ISSUE TITLE
Additional information of aliased states

### ISSUE THREAD

**Issue by braindead1** [ioBroker/ioBroker.devices#22]
_This issue is not a bug. It is meant as continuation of a discussion I started via telegram._

I'm currently working on a new visualization that will not be based on single states like VIS. It will be based on devices like iQontrol. Instead of having the configuration of devices as part of the adapter configuration (like in iQontrol) I want to use devices created by this adapter.

Problem: If I create thermostat devices for my HomeMatic thermostats, the created states do not automatically take over e.g. min and max temperatures. It's the same for dimmers and potentially other devices as well. These values are important to be known in the visualization to send correct values back to ioBroker.

From my point of view there are 3 ways to handle this problem:
1. After fetching the alias devices and their states in the visualization, also fetch the information of the aliased states.
2. Force the user to manually edit the created states and enter the needed information. This can either be done after creating the devices via the object tree or this can be done as part of the device creation.
3. Automatically take over parts of the aliased states and update this data in case the aliased state is updated.

What should be the proposed way to handle this problem?

**Comment by 5G7K** [comment]
I have exactly the same problem. MIN, MAX, STEP were not taken over and therefore visualization in lovelace does not work.
After adding these vales manually to the new alias DP everything works fine.

Disadvantages:
-you have to realize that (why does it not work...?)
-you have to maintain MIN, MAX, etc. twice in the original DP and in the Alias which is created by Devices
