### ISSUE TITLE
Can't install adapter 

### ISSUE THREAD

**Issue by TemPeck** [ioBroker/ioBroker.devices#24]
Hello,

I can't install the adapter and I don't know why...

Seems to be like issue #16.

Betriebssystem: linux (Proxmox VM)
Admin v. 4.1.6
NPM: 6.13.4
Node: 10.19.0

Thank's for support....
Antwort auch gerne auf deutsch, je nach Belieben :)

This is the log:
`host.iobroker | 2020-08-02 00:41:03.699 | info | iobroker exit 0
-- | -- | -- | --
host.iobroker | 2020-08-02 00:41:02.689 | info | iobroker host.iobroker object system.adapter.devices.0 created
host.iobroker | 2020-08-02 00:41:02.679 | info | iobroker host.iobroker create instance devices
host.iobroker | 2020-08-02 00:41:02.671 | info | iobroker INFO: Directory "/opt/iobroker/node_modules/iobroker.devices/www" was not found! Nothing was uploaded or deleted.
host.iobroker | 2020-08-02 00:41:02.596 | info | iobroker host.iobroker object system.adapter.devices created/updated
host.iobroker | 2020-08-02 00:41:02.490 | info | iobroker INFO: Directory "/opt/iobroker/node_modules/iobroker.devices/www" was not found! Nothing was uploaded or deleted.
host.iobroker | 2020-08-02 00:41:02.435 | info | iobroker upload [0] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/asset-manifest.json asset-manifest.json application/json
host.iobroker | 2020-08-02 00:41:02.381 | info | iobroker upload [1] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/devices.png devices.png image/png
host.iobroker | 2020-08-02 00:41:02.327 | info | iobroker upload [2] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
host.iobroker | 2020-08-02 00:41:02.273 | info | iobroker upload [3] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/index.html index.html text/html
host.iobroker | 2020-08-02 00:41:02.218 | info | iobroker upload [4] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/index_m.html index_m.html text/html
host.iobroker | 2020-08-02 00:41:02.164 | info | iobroker upload [5] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/manifest.json manifest.json application/json
host.iobroker | 2020-08-02 00:41:02.110 | info | iobroker upload [6] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/precache-manifest.c07dc12a1069de05f83c58f063a4d4cc.js precache-manifest.c07dc12a1069de05f83c58f063a4d4cc.js applica
host.iobroker | 2020-08-02 00:41:02.056 | info | iobroker upload [7] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/service-worker.js service-worker.js application/javascript
host.iobroker | 2020-08-02 00:41:02.001 | info | iobroker upload [8] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/css/2.c304fab6.chunk.css static/css/2.c304fab6.chunk.css text/css
host.iobroker | 2020-08-02 00:41:01.947 | info | iobroker upload [9] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/css/2.c304fab6.chunk.css.map static/css/2.c304fab6.chunk.css.map application/json
host.iobroker | 2020-08-02 00:41:01.785 | info | iobroker upload [10] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.5cc5e605.chunk.js static/js/2.5cc5e605.chunk.js application/javascript
host.iobroker | 2020-08-02 00:41:01.730 | info | iobroker upload [11] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.5cc5e605.chunk.js.LICENSE.txt static/js/2.5cc5e605.chunk.js.LICENSE.txt text/plain
host.iobroker | 2020-08-02 00:41:01.039 | info | iobroker upload [12] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/2.5cc5e605.chunk.js.map static/js/2.5cc5e605.chunk.js.map application/json
host.iobroker | 2020-08-02 00:41:00.981 | info | iobroker upload [13] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/main.4aad0d32.chunk.js static/js/main.4aad0d32.chunk.js application/javascript
host.iobroker | 2020-08-02 00:41:00.912 | info | iobroker upload [14] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/main.4aad0d32.chunk.js.map static/js/main.4aad0d32.chunk.js.map application/json
host.iobroker | 2020-08-02 00:41:00.854 | info | iobroker upload [15] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/runtime-main.15dce915.js static/js/runtime-main.15dce915.js application/javascript
host.iobroker | 2020-08-02 00:41:00.799 | info | iobroker upload [16] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/js/runtime-main.15dce915.js.map static/js/runtime-main.15dce915.js.map application/json
host.iobroker | 2020-08-02 00:41:00.744 | info | iobroker upload [17] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/static/media/copy-content.6fe0b363.svg static/media/copy-content.6fe0b363.svg image/svg+xml
host.iobroker | 2020-08-02 00:41:00.688 | info | iobroker upload [18] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/tab.html tab.html text/html
host.iobroker | 2020-08-02 00:41:00.581 | info | iobroker upload [19] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/vendor/socket.io.js vendor/socket.io.js application/javascript
host.iobroker | 2020-08-02 00:41:00.430 | info | iobroker host.iobroker install adapter devices
host.iobroker | 2020-08-02 00:40:39.702 | info | iobroker npm install iobroker.devices@0.3.6 --loglevel error --prefix "/opt/iobroker" (System call)
host.iobroker | 2020-08-02 00:40:39.700 | info | iobroker NPM version: 6.13.4
host.iobroker | 2020-08-02 00:40:37.763 | info | iobroker add devices --host iobroker`

**Comment by Apollon77** [comment]
Was genau ist das Problem? Installation erfolgreich. Bitte devices Tab einblenden das es im Menü links erscheint.

**Comment by TemPeck** [comment]
Es erschien bis eben nicht in der Auswahlliste. Ich habe eben zum Probieren daraufhin in der Liste "Ereignisse" aktiviert (hatte ich sonst nicht), daraufhin ist der Auswahlpunkt erschienen. 
Nunmehr also gelöst, warum auch immer es vorher nicht ging... 

Vielen Dank!
