### ISSUE TITLE
Thermostat 

### ISSUE THREAD

**Issue by MikeHellracer** [ioBroker/ioBroker.devices#25]
Bei der Verwendung von Thermostat 

**To Reproduce**  
Thermostat erstellen und Ziele setzen. 
Öffne von Thermostat (info) 
Anstatt "Power" und "Boost" sind beide "Actual"
Ziel für "Power" = "Boost" 
Bei edit von power wird boost automatisch mit demselben Ziel befüllt 
Der Value für Power wird unter objekte gar nicht gesetzt. 

** Screenshots **
Actual, power, boost
![Screenshot_20200809_104128_com android chrome](https://user-images.githubusercontent.com/59908487/89728351-00cc6480-da2d-11ea-8425-b163452509b7.jpg)

Value nicht gesetzt
![Screenshot_20200809_103704](https://user-images.githubusercontent.com/59908487/89728285-77b52d80-da2c-11ea-9a15-6cedc28bd033.jpg)

**Expected behavior**  
Ich vermute es handelt sich um ein generelles Problem. 

**Versions:**  
 - everything is up to date (08.08.2020l

**Additional context**  
Als Ziel wurden 2 verschiedene Adapter (broadlink & midea) verwendet. Bei beiden kommt das gleiche Fehlerbild

**Comment by GermanBluefox** [comment]
Should be fixed in new version

**Comment by GermanBluefox** [comment]
Fixed in 1.0.x. Please verify
