### ISSUE TITLE
Icon smoke Detector

### ISSUE THREAD

**Issue by MikeHellracer** [ioBroker/ioBroker.devices#26]
**Describe the bug**  
Nach der Erstellung eines rauchmelders wird als. Icon eine Tür angezeigt. 

**To Reproduce**  
1. Rauchmelder eratellen

**Expected behavior**  
Icons für Rauchmelder (an/aus) sollen angezeigt werden

**Screenshots & Logfiles**  
![Screenshot_20200809_104332_com android chrome](https://user-images.githubusercontent.com/59908487/89728428-99fb7b00-da2d-11ea-9a2b-203999723e09.jpg)

**Versions:**  
 - everything is up to date 08.08.2020

**Additional context** 
. Vlt kann man den Editor auf das IconVerzeichnis von iobroker verweisen lassen?

**Comment by GermanBluefox** [comment]
Fixed in 1.0.x. Please verify
