### ISSUE TITLE
[Request] Device Type white color light

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.devices#27]
Would it be possible to get a device type for white color lights?

With the states colortemp, dimmer and state. Just like the RGB single but without the RGB

Thank you :)

**Comment by GermanBluefox** [comment]
Do you mean RGBW?

**Comment by Hesse-Bub** [comment]
No, just white (wihtout RGB) ... for RGB color is mendatory.

Just with the states colortemp, dimmer and state.

**Comment by GermanBluefox** [comment]
It is "ct".
![image](https://user-images.githubusercontent.com/4582016/121225623-ff0c4100-c889-11eb-87b0-6256da630968.png)

And it was already implemented
