### ISSUE TITLE
Handling of Unwanted Native Devices - Delete / Hide Option

### ISSUE THREAD

**Issue by Percy2Live** [ioBroker/ioBroker.devices#273]
I noticed that my native device folder is full by default with my homematic devices. This also floods the list of available devices on my amazon echo. All of these devices do not make sense in my setup, so I would like to get rid of them.

Unfortunately there is neither an option to disable these native devices in the homematic adapters, nor in the device adapter. I cannot even delete these automatically created devices. Even if I just want to hide them on my amazon echo, I need to click through 40+ entries in the list to hide them from my smart assistent.

![image](https://github.com/ioBroker/ioBroker.devices/assets/63621052/a7439cba-55df-44e2-83b1-12d74d864adc)

A solution to select native devices or at least allow the user to delete them would be great

**Comment by Apollon77** [comment]
I think you missunderstand the meaning of "native devices". they are nothing bad or such. These are just devices defined by adapters themself and not aliases. This List is there to allow an easy creation of aliases for them ... Or why you have an issue with this list?

**Comment by Percy2Live** [comment]
Each device has enbled this setting which makes it visible for my smart assistent:

![image](https://github.com/ioBroker/ioBroker.devices/assets/63621052/37e759a2-f2c9-4c47-a516-b6b26bfe1bfc)

To disable this, I need to manually click on each entry. I understand your point about not being able to delete these devices

**Comment by Apollon77** [comment]
Or you set in iot that he should NOT use rooms and fucntions to automatically add devices ... then you can ad each manually, but this has nothing to do with the devices adapter :) When it is iot adapter
