### ISSUE TITLE
Klimaanlage Bug

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.devices#29]
V0.3.13

folgende Einstellung verursacht nachfolgenden Fehler, der Wert ist eigentlich eine Nummer wird aber auf Null % umgeschrieben
![image](https://user-images.githubusercontent.com/25475385/92464785-f210d300-f1cd-11ea-98df-9abcad2feaac.png)
![image](https://user-images.githubusercontent.com/25475385/92464794-f5a45a00-f1cd-11ea-9835-29b7d309ed84.png)

**Comment by Apollon77** [comment]
Closed because?

BTW the role level.mode.fan and level.mode.thermostat are not valid ones!

**Comment by duczz** [comment]
War ein Script Fehler
