### ISSUE TITLE
Failed to install adapter

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.devices#293]
Failed to install adapter

log:

host.IOBroker install adapter devices
upload [132] devices.admin /opt/iobroker/node_modules/iobroker.devices/admin/asset-manifest.json asset-manifest.json application/json
/usr/bin/iobroker: Zeile 10:  1530 Getötet                node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js "$@"
iobroker@IOBroker:~$

**Versions:**  
 - Adapter version: 1.1.5
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: Linux

**Comment by Apollon77** [comment]
Please try again? Something killed te nodejs process

**Comment by Dome2075** [comment]
[Solved]

Hello,

I tryed reinstall several times with no positiv result.

now i  delete object "alias"( because of old states from alias adapter) and now it works to install.
