### ISSUE TITLE
alias object name will be cleared after I press OK button

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.devices#3]
I create a alias device, set device name, and set device state objects.
Then I press OK
![image](https://user-images.githubusercontent.com/4982108/64443201-05451a80-d104-11e9-9fcb-71f8a8d5a891.png)

No response. And the log shows
![image](https://user-images.githubusercontent.com/4982108/64443325-3de4f400-d104-11e9-8f71-cc18f21f939b.png)

Then I cancel this config, I found the object name is cleared
![image](https://user-images.githubusercontent.com/4982108/64443030-9f589300-d103-11e9-95ba-6302a8ef9696.png)

**Comment by SchumyHao** [comment]
I found when I press OK button
There will be an error
![image](https://user-images.githubusercontent.com/4982108/64477342-fc6c4b80-d1cc-11e9-9892-3e4360269537.png)
In ListDevices.js +880
data has no member named `function`

**Comment by SchumyHao** [comment]
Patch commited, Need your review
https://github.com/ioBroker/ioBroker.devices/pull/1/commits/d5c0d749e71f920c21c4c42d13b88147e09f9c51

**Comment by GermanBluefox** [comment]
Thank you.
