### ISSUE TITLE
[Improvement] Custom fields to extend devices

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#31]
Hi,

some devices have more states than supported by the devices created by the Alias adapter eg. Zigbee has link quality or battery voltage and percentage.

Could you add the possibility to have own custom states added by the user and those linked to states of the actual devices.

Thanks
Martin

**Comment by martinschm** [comment]
still open

**Comment by martinschm** [comment]
Works with this adapter: https://github.com/sbormann/ioBroker.alias-manager

**Comment by GermanBluefox** [comment]
Fixed in 1.0.x. Please verify
