### ISSUE TITLE
[Improvement] Easier conversion of fields

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#32]
Hi,

some devices offer battery percentage instead of lowbat or an availability state instead of unreach. 

In other adapters e,g, iQontrol users can simply invert values with a tick box instead of entering functions.
This would increase the usability by a huge step.

Best
Martin

**Comment by martinschm** [comment]
Boost

**Comment by GermanBluefox** [comment]
In my opinion, the adapters must create additional states low_bat alarm, parallel to battery_voltage, as the critical level is for every device is different.
