### ISSUE TITLE
Double entry for some devices

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#33]
**Describe the bug**  
For some devices created through the adapter suddenly there appears a second entry.

**To Reproduce**  
Create device, save adapter settings, re open adapter. If the device has two functions or simply one of the states has a second function a second entry is created in the device overview.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/39886158/94999461-da085580-05b9-11eb-8734-c40d4fd8ccc2.png)

**Versions:**  
Ubuntu 20.04, nodejs v12.18.4, manage devices 0.3.6

**Comment by micklafisch** [comment]
I can confirm this bug.

If i change i.e. the function of the device, this device will be shown two times in section alias but both with the new function:

![grafik](https://user-images.githubusercontent.com/44931749/100602628-6f973b80-3304-11eb-8e63-307a5f7c3f4a.png)

**Comment by GermanBluefox** [comment]
Should be fixed in the new version
