### ISSUE TITLE
Unknown type floodAlarm

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#34]
Hi,

I tried to add a water sensor and I get the message "unknown type floodAlarm".
Is it possible to add it or at least remove the option to add one.

![image](https://user-images.githubusercontent.com/39886158/95575313-bff1cb80-0a2e-11eb-9aeb-53bf732e59d6.png)

**Comment by martinschm** [comment]
Same happens for fireAlarm.

@Apollon77: Is there any way I can help to add these types?
Not a programmer but if it is about creating some entries I think I could do that.

**Comment by martinschm** [comment]
Problem still exists

**Comment by martinschm** [comment]
Possible to add with this adapter: https://github.com/sbormann/ioBroker.alias-manager

**Comment by GermanBluefox** [comment]
Duplicate https://github.com/ioBroker/ioBroker.devices/issues/8
