### ISSUE TITLE
Alias xyz has no target 12

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#35]
Hi,

when creating new Aliases I find these warnings in the log coming from other adapters.
I am aware this might not be a bug but is just a warning but I was surprised to see these warnings coming from other adapters which do not even use the Aliases at the moment.

`
influxdb.0 | 2020-10-10 09:43:02.358 | warn | (581462) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12
-- | -- | -- | --
javascript.0 | 2020-10-10 09:43:02.358 | warn | (2019874) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12
web.0 | 2020-10-10 09:43:02.354 | warn | (580012) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12

`

**Comment by Apollon77** [comment]
Please Show the object definition of the affected object - objects, pencil icon, raw tab. It seems that the alias is not setup correctly

**Comment by martinschm** [comment]
Double posting du to github problem see #36
