### ISSUE TITLE
Alias has no target 12

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#36]
Hi,

when creating new Aliases I find these warnings in the log coming from other adapters.
I am aware this might not be a bug but is just a warning but I was surprised to see these warnings coming from other adapters which do not even use the Aliases at the moment.

`
influxdb.0 | 2020-10-10 09:43:02.358 | warn | (581462) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12
-- | -- | -- | --
javascript.0 | 2020-10-10 09:43:02.358 | warn | (2019874) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12
web.0 | 2020-10-10 09:43:02.354 | warn | (580012) Alias alias.0.Tueren.Garagentor.ACTUAL has no target 12

`

**Comment by Apollon77** [comment]
Please Show the object definition of the affected object - objects, pencil icon, raw tab. It seems that the alias is not setup correctly

**Comment by martinschm** [comment]
Hi @Apollon77 
here it is

`{
  "_id": "alias.0.Tueren.Garagentor.ACTUAL",
  "common": {
    "name": "ACTUAL",
    "role": "sensor.door",
    "type": "boolean",
    "read": true,
    "write": false,
    "alias": {
      "id": "zigbee.0.00158d0001b95702.opened"
    }
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1602315782348,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Apollon77** [comment]
hm ... should be ok ... please restart influxdb adapter ... then error still there?

**Comment by foxriver76** [comment]
I don't know how the devices adapter work, but can it be that the object is created w/o `alias` and then it is extended? If this is the case, at the first creation the adapters will log this. As soon as it is extended with an existing target the logging should no longer appear.

**Comment by Wildbill-Z** [comment]
Today I installed this adapter and I am also getting the errors "target 12" when setting up a new alias. [HERE](https://forum.iobroker.net/topic/27276/gel%C3%B6st-alias-alias-0-has-no-target-12-im-log/10) in iobroker forum I described it all (in German, but the logs and objects should be self-explanatory?!
Greetings
