### ISSUE TITLE
[Enhancement] Add states for thermostate

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#38]
Hi,

could you please add states/fields for the device type "thermostate":

Homematic thermostate have modes like (manual, automatic, boost) or Party mode.

Thanks
Martin

**Comment by martinschm** [comment]
Still open

**Comment by GermanBluefox** [comment]
Like this one?
![image](https://user-images.githubusercontent.com/4582016/121226131-8063d380-c88a-11eb-8adf-3cda0796e994.png)
