### ISSUE TITLE
Fire alarm aliases end up in info folder

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.devices#40]
When creating Aliases of the type Firealarm they are not added into a separate folder but end up in the info folder. This is confusing as all the other sensors seem to be put into type specific folders

![image](https://user-images.githubusercontent.com/39886158/97082827-c4aca700-160c-11eb-946c-0b8ae6a0f4f6.png)

**Comment by GermanBluefox** [comment]
In der neuen Version gibt es keine Möglichkeit mehr nach Funktionen zu gruppieren.
Dafür kann man eigene Folder-Struktur erzeugen.
