### ISSUE TITLE
Device installiert aber es wird nicht gestartet 

### ISSUE THREAD

**Issue by B4unty** [ioBroker/ioBroker.devices#44]
Hallo zusammen ich habe den Apdapter installiert aber bekomme den nicht angezeigt, ich habe auch nur den schlüssel und den mülleimer alles andere fehlt. 
![grafik](https://user-images.githubusercontent.com/22129987/98544488-629ea380-2294-11eb-9b3e-f1292ca0753c.png)

**Comment by Apollon77** [comment]
This completely correct. Enable the Devices Tab - devices is not having any server side component and completely runs in admin
