### ISSUE TITLE
Devices list is empty

### ISSUE THREAD

**Issue by Bart1909** [ioBroker/ioBroker.devices#47]
I have already created some aliases. This aliases were created via Javascript with [this script](https://forum.iobroker.net/topic/27295/vorlage-alias-per-skript-erzeugen)

Now I installed the devices adapter (version 0.3.13).
But when I open the devices tab, the list is empty:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/14097923/101240408-89af9000-36ef-11eb-8d8b-5a1da8b81f0f.png">

As you see in the screenshot, the browser console is not showing any errors.

I tried Safari and Chrome browser, as well as light & dark theme.

My existing aliases.0 states look like this:
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/14097923/101240517-d004ef00-36ef-11eb-9a28-ea7159743750.png">

**Comment by GermanBluefox** [comment]
Aliases must have specific structure and settings to be detected by alexa and "devices" adapter.
Please use "devices" adapter to create the device, that will be supported by Alexa
