### ISSUE TITLE
Multi level hierarchy

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.devices#48]
**Describe the bug**  
Only one layer of folders is possible.

**To Reproduce**  
1. Create a directory (e.g. "Hallway") within Root inside the adapter
2. create a directory (e.g. "Lighting") within the "Hallway" directory
3. try to create a device within the "Lighting" directory. It won't be visible

**Expected behavior**  
Creating a multi level hierarchy should be possible.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/13995942/102724578-d78fdf00-4310-11eb-9f40-2e53ba59f1a4.png)

**Versions:**  
 - Adapter version: 0.3.15
 - JS-Controller version: 3.1.6
 - Node version: v10.22.1
 - Operating System: Debian GNU/Linux 10 (buster)
 - Kernel: Linux 4.19.0-11-amd64
 - Architecture: x86-64

**Comment by grdminer** [comment]
Same here. I've created a mutli level folder structure in an older version. It's not accessible anymore. It's still possible to create subfolder but they wont show up.

**Comment by FISO291** [comment]
Bei mir auch das gleiche. Irgendwie hab ich die Version Adapter version: 0.3.6 zerschossen... Wenn ich auf "+" klicke kommt garnichts mehr!

**Comment by GermanBluefox** [comment]
In progress.
![image](https://user-images.githubusercontent.com/4582016/120085154-05eec300-c0d6-11eb-879f-d97261665708.png)
