### ISSUE TITLE
Liste Gerätetyp

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.devices#52]
Hallo
In der Geräteliste gibt es den Punkt "Instanz" - wenn man die jedoch  auswählt, kommt die Felermeldung "Unknown type!instance".

Zudem würde es mich freuen wenn noch ein paar Geräte wie Fernseher, CO2 Melder, Rauchmelder, Glasbruchmelder, etc hinzugefügt würde.

Ebenso wäre ich froh, wenn beim Temp Snsor auch gleich die Luftfeuchtigkeit angegeben werden könnte...

Besten Dank im Voraus
Matt

**Comment by GermanBluefox** [comment]
Man kann schon zu Temperature die Luftfeuchtigkeit eingeben.
![image](https://user-images.githubusercontent.com/4582016/120085075-7ea14f80-c0d5-11eb-93d2-f95969086594.png)

Instanz wird gelöscht.

Wo willst du (Fernseher, CO2 Melder, Rauchmelder, Glasbruchmelder, etc) verwenden? Alexa &Co und Material unterstützen das nicht....
