### ISSUE TITLE
The devices tab does not open.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.devices#54]
**Describe the bug**  
If there is a "broken" device, the devices tab does not open.

**To Reproduce**  
Unfortunately, I can't reproduce the error. I can share a screenshot of the error.

**Expected behavior**  
check for "broken" devices and issue a warning that the device needs to be "fixed".

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/110662117-41b07580-81d6-11eb-896c-4920f808dd44.png)

**Versions:**  
 - Adapter version: 0.3.15
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: mac os

**Comment by Apollon77** [comment]
Could it be that you have a ")" in an object name??

**Comment by GermanBluefox** [comment]
Try to test 0.3.16
