### ISSUE TITLE
A more flexible GUI

### ISSUE THREAD

**Issue by Videonisse** [ioBroker/ioBroker.devices#55]
As a non Developer and a user who prefers a Graphical User Interface before using scripts and edit XML files, I would love if the GUI for creating Devices based on Alias or LinkedDevices could use the same flexibility as the HomeKit Yahka Adapter.

Some of the features in Yahka that I miss with the Devices GUI, or that I think is needed to support the various needs of today's users are:

- Devices should be able to have multiple service types and not just one. Each service belongs to a Channel. 
- Standard Templates are used to create Devices and Services and they define both mandatory and optional objects.
- It should be possible to add custom templates with custom objects, and they should be able to inherit objects from standard templates
- Be able to copy a current Device, including the Services, to create new ones.
- Enable/disable an Object, Service/Channel  etc without deleting the data
- ObjectID should be a UUID and don't have any relations to Device or Channel Name, Location or Role. It must be fully flexible to change the name and the other metadata without having a conflict with the current ObjectID!
- If possible, it would be great if Homekit, Google Home, Alexa etc could be enabled directly from the Devices GUI instead of creating the Devices/Skills etc from another GUI.
- 
- **Use OCF** as a base for how Device and Service (Resource) Types are defined: https://openconnectivity.org/

As an example, the GUI from Homekit Yahka Adapter (v0.13.1):

![2021-03-15 17_26_44-instances - ioBroker](https://user-images.githubusercontent.com/13684218/111192255-28823d00-85b9-11eb-9dde-3e9c2b77a384.png)

Yahka Adapter GitHub: https://github.com/jensweigele/ioBroker.yahka/blob/master/README.md

**Comment by Videonisse** [comment]
Regarding Templates, example how Open Connectivity Foundation define **Device Type "Light"**:
```
{
     "devicename": "Light",
     "devicetype": "oic.d.light",
     "vertical":   "Smart Home",
     "resources": [
       {"resourcetypetitle": "Binary Switch", "resourcetypeid": "oic.r.switch.binary"}
     ],
     "recommendedresources": [
       {"resourcetypetitle": "Colour Hue Saturation", "resourcetypeid": "oic.r.colour.hs"},
       {"resourcetypetitle": "Colour Space Co-ordinates", "resourcetypeid": "oic.r.colour.csc"},
       {"resourcetypetitle": "Colour Temperature", "resourcetypeid": "oic.r.colour.colourtemperature"},
       {"resourcetypetitle": "Dimming", "resourcetypeid": "oic.r.light.dimming"},
       {"resourcetypetitle": "Ramp Time", "resourcetypeid": "oic.r.light.ramptime"}
     ]
   }
```
Source: https://github.com/openconnectivityfoundation/devicemodels/blob/master/oic.devicemap-content.json


Example oic.r.light.dimming:
```
{
  "swagger": "2.0",
  "info": {
    "title": "Dimming",
    "version": "2019-02-15",
    "license": {
      "name": "OCF Data Model License",
      "url": "https://github.com/openconnectivityfoundation/core/blob/e28a9e0a92e17042ba3e83661e4c0fbce8bdc4ba/LICENSE.md",
      "x-copyright": "copyright 2016-2017, 2019 Open Connectivity Foundation, Inc. All rights reserved."
    },
    "termsOfService": "https://openconnectivityfoundation.github.io/core/DISCLAIMER.md"
  },
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/DimmingResURI" : {
      "get": {
        "description": "This Resource describes a dimming function.\nThe Property \"dimmingSetting\" is an integer showing the current dimming level.\nIf Property \"step\" is present then it represents the increment between dimmer values.\nWhen the Property \"range\" is omitted, then the range is [0,100].\nA value of 0 means total dimming; a value of 100 means no dimming.",
        "parameters": [
          {"$ref": "#/parameters/interface"}
        ],
        "responses": {
            "200": {
              "description" : "",
              "x-example":
                {
                  "rt": ["oic.r.light.dimming"],
                  "if": ["oic.if.a", "oic.if.baseline"],
                  "dimmingSetting": 30,
                  "step": 5,
                  "range": [0, 100]
                },
              "schema": { "$ref": "#/definitions/Dimming" }
            }
        }
      },
      "post": {
        "description": "Sets the desired dimming level.\n",
        "parameters": [
          {"$ref": "#/parameters/interface"},
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Dimming" },
            "x-example":
              {
                "dimmingSetting": 40
              }
          }
        ],
        "responses": {
            "200": {
              "description" : "Indicates that the dimming was changed.\nThe new dimming level is provided in the response.\n",
              "x-example":
                {
                  "dimmingSetting": 40
                },
              "schema": { "$ref": "#/definitions/Dimming" }
            },
            "403": {
              "description": "This response is generated by the OCF Server when the client sends:\n  An update with an out of range property value for dimmingSetting.\nThe server responds with the current resource representation.\n",
              "x-example":
                {
                  "dimmingSetting": 40
                },
              "schema": { "$ref": "#/definitions/Dimming" }
            }
        }
      }
    }
  },
  "parameters": {
    "interface": {
      "in": "query",
      "name": "if",
      "type": "string",
      "enum": ["oic.if.a", "oic.if.baseline"]
    }
  },
  "definitions": {
    "Dimming" : {
      "properties": {
        "rt": {
          "description": "The Resource Type.",
          "items": {
            "enum": ["oic.r.light.dimming"],
            "maxLength": 64,
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true,
          "readOnly": true,
          "type": "array"
        },
        "dimmingSetting": {
          "description": "The current dimming value.",
          "type": "integer"
        },
        "n": {
            "$ref": "https://openconnectivityfoundation.github.io/core/schemas/oic.common.properties.core-schema.json#/definitions/n"
        },
        "id": {
            "$ref": "https://openconnectivityfoundation.github.io/core/schemas/oic.common.properties.core-schema.json#/definitions/id"
        },
        "range": {
            "$ref": "https://openconnectivityfoundation.github.io/IoTDataModels/schemas/oic.baseresource.properties-schema.json#/definitions/range_integer"
        },
        "step": {
            "$ref": "https://openconnectivityfoundation.github.io/IoTDataModels/schemas/oic.baseresource.properties-schema.json#/definitions/step_integer"
        },
        "if": {
          "description": "The OCF Interface set supported by this Resource.",
          "items": {
            "enum": [
              "oic.if.a",
              "oic.if.baseline"
            ],
            "type": "string"
          },
          "minItems": 2,
          "uniqueItems": true,
          "readOnly": true,
          "type": "array"
        }
      },
      "type": "object",
      "required": ["dimmingSetting"]
    }
  }
}
```
Source: https://openconnectivityfoundation.github.io/IoTDataModels/DimmingResURI.swagger.json

**Comment by GermanBluefox** [comment]
Many requests are implemented:
- *Devices should be able to have multiple service types and not just one.*
   You can add device to multiple enumerations. But thermostat cannot be a dimmer.
- *Standard Templates are used to create Devices and Services and they define both mandatory and optional objects.*
  That works from the beginning.
- *It should be possible to add custom templates with custom objects, and they should be able to inherit objects from standard templates* 
  You can extend standard types with own states.
- *Enable/disable an Object, Service/Channel etc without deleting the data*
  Not implemented as use case is unclear
- *Be able to copy a current Device, including the Services, to create new ones.*
   Clone functionality is implemented
- *ObjectID should be a UUID and don't have any relations to Device or Channel Name, Location or Role. It must be fully flexible to change the name and the other metadata without having a conflict with the current ObjectID!*
  UUID is hard to read for people. But you can create multi-level structure with devices that has any names (defined by human)
- *If possible, it would be great if Homekit, Google Home, Alexa etc could be enabled directly from the Devices GUI instead of creating the Devices/Skills etc from another GUI.* 
 all devices, that created, cloned in aliases are automatically available in Alexa, Google, Material. (Homekit must be rewritten)
- *Use OCF as a base for how Device and Service (Resource) Types are defined: https://openconnectivity.org/*
 I prefer [Alexa API](https://developer.amazon.com/de-DE/docs/alexa/device-apis/smart-home-general-apis.html) and [Google Home API](https://developers.google.com/assistant/smarthome/guides)
