### ISSUE TITLE
Tab does not open

### ISSUE THREAD

**Issue by realhawker** [ioBroker/ioBroker.devices#58]
**Describe the bug**  
When I open the devices tab it is empty

**To Reproduce**  
1. Go to devices

**Expected behavior**  
The devices tab with all devices is shown.

**Screenshots & Logfiles**  
![Screenshot 2021-04-30 210059](https://user-images.githubusercontent.com/4715835/116742136-3d931e00-a9f7-11eb-8118-234efd291248.png)

**Versions:**  
 - Adapter version: 0.3.16
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: raspbian

**Comment by Apollon77** [comment]
Bitte mal "iobroker upload devices" ausfühhren. Ist es dann da?

**Comment by realhawker** [comment]
Das hat funktioniert. Vielen Dank.
