### ISSUE TITLE
Please add a gate.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.devices#64]
Describe the bug
When I try to create a gate in the "devices", an error Unknown type!gate appears.

To Reproduce

Go to 'devices'
Click on '+'
Add Gate
See error
Expected behavior
Add gate to the Google home and Yandex Alice.

Screenshots & Logfiles
![image](https://user-images.githubusercontent.com/37106885/118555082-e7e6a180-b76a-11eb-9ae4-27b3a68afa2b.png)
Versions:

Adapter iot version: 1.8.16
Adapter devices version: 0.3.16
JS-Controller version: 3.2.16
Node version: v12.21.0
Operating system: debian

and it would be just great if you could create a gate in which you only need to specify the objects "button", "end cap open", "end cap closed". At the same time, if it is possible to indicate how many endpoints there actually are, it would be just fantastic! I attach two examples of the script.
[Ворота.txt](https://github.com/ioBroker/ioBroker.devices/files/6496841/default.txt)
[Garagentor.txt](https://github.com/ioBroker/ioBroker.devices/files/6496842/Garagentor.txt)

**Comment by GermanBluefox** [comment]
No it is not possible. "button", "end cap open", "end cap closed"
Every gate acts different. Devices has no logic and even no backend.
Why you don't implement logic in javascript???

**Comment by Anzic23** [comment]
> No it is not possible. "button", "end cap open", "end cap closed"
> Every gate acts different. Devices has no logic and even no backend.
> Why you don't implement logic in javascript???

i do )
I wish it could be done in the adapter. Well, let's hope that there will be some kind of adapter for this, because the logic of the gate is almost always the same. Or I will continue to use the script.
