### ISSUE TITLE
Version 1.0.1 didn't show anything in old and new UI (never stop circling the update icon)

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.devices#71]
**Describe the bug**  
Can'r see anything. Tested in old and new UI

**To Reproduce**  
simple upgrade to 1.0.1

**Expected behavior**  
Have to work ;-)

**Screenshots & Logfiles**  
Nothing to show

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: <js-controller-version> 3.2.16
 - Node version: <node-version> 12.22.1
 - Operating system: Linux

**Additional context**  
Nothing in log related to devices, except upgrade/downgrade of adapter

**Comment by mcuiobroker** [comment]
Same as above with admin 4.2.1

**Comment by GermanBluefox** [comment]
I cannot do anything, as I don't have any error messages.

Please provide browser console errors. And please reproduce the error with opened browser console (press F5 before reproducing)
Only when browser console is opened from the beginning (including loading of the page) the error code could be decoded into error message.

**Comment by PeterVoronov** [comment]
> I cannot do anything, as I don't have any error messages.
> 
> Please provide browser console errors. And please reproduce the error with opened browser console (press F5 before reproducing)
> Only when browser console is opened from the beginning (including loading of the page) the error code could be decoded into error message.

There is a log.

Possible, I know the reason, as I have more then 2 (up to 5) 
[iot-main.catshome.name-1623173305627.log](https://github.com/ioBroker/ioBroker.devices/files/6618552/iot-main.catshome.name-1623173305627.log)
nested levels ..

**Comment by GermanBluefox** [comment]
All what I need is:
`ListDevices.js:215 Uncaught (in promise) TypeError: Cannot read property 'linkeddevices.0.people.family' of undefined
    at ListDevices.js:215`, but than you anyway

**Comment by GermanBluefox** [comment]
Fixed in 1.0.2

**Comment by Anzic23** [comment]
I confirm that in 1.0.2 the problem disappeared, on 1.0.1 it was the same as in topikstarter

**Comment by PeterVoronov** [comment]
> Fixed in 1.0.2

thnks

**Comment by mcuiobroker** [comment]
Problem with 1.0.4
![image](https://user-images.githubusercontent.com/84818934/121391520-c08c8a00-c94e-11eb-89e4-51953bfbd7a9.png)
