### ISSUE TITLE
if alias.0 is completely empty it is impossible to add alias devices

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.devices#78]
**Describe the bug**  
If alias.0 is completely empty it is impossible to add alias devices, because "native devices" is always selected and can not be unselected.

Workaround: create empty folder in alias.0, which shows up in devices view and 

**To Reproduce**  
1. Empty alias.0 (or start fresh, for example with dev-server or similar)
2. Open devices tap
3. See that 'native devices' is selected and create alias device / create folder are disabled.

**Expected behavior**  
Suggestion: do not disable the "create folder" button but create folder in root if native devices is selected? Or add another "dummy" entry for root folder that allows to create folders... not sure what is best. Anayway, it should be possible to add folders and alias device even if alias.0 is empty.

**Screenshots & Logfiles**  
![issue-create-device-folder-disabled](https://user-images.githubusercontent.com/620860/123860839-beeb2c00-d926-11eb-9ac7-73495dcc0c43.JPG)

In screenshot you can see the situation -> only "native devices" is there, the +-buttons are disabled and I can not select anything else, because there is nothing.

**Versions:**  
 - Adapter version: 1.0.6
 - JS-Controller version: 3.3.14
 - Node version: 14.16.0
 - Operating system: Windows 10 / Ubuntu 20.04

**Comment by GermanBluefox** [comment]
Please test 1.0.7

**Comment by Garfonso** [comment]
Works. 😄 

I like how the Tooltip of new folder changes to "Create new folder in root". Not sure if the disabled tooltip of the create device button could need a little more help, too.
