### ISSUE TITLE
Devices are not displayed

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.devices#79]
**Describe the bug**  
After I installed the device adapter yesterday, I first had the problem that I could not create folders and devices. By manually adding a folder under objects alias.0 I was then able to create devices and folders.
Now I created the folders as in the screenshot (see below) and also added 6 devices. However, these are not displayed in the devices menu. Under Objects, however, they are (see also below).

**Expected behavior**  
Normally, the devices should be displayed as in the native devices folder.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/19261667/123923217-13bf8e80-d989-11eb-91c9-901a35326c32.png)
![image](https://user-images.githubusercontent.com/19261667/123923262-1de18d00-d989-11eb-8434-89a4ea8cd29d.png)

**Versions:**  
 - Adapter version: 1.0.6
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container

**Additional context**  
When I want to export the directory tree alias under objects as JSON I get the following code. There is nothing about the created devices.
```
{
  "alias.0": {
    "_id": "alias.0",
    "type": "meta",
    "common": {
      "name": {
        "en": "Aliases' root folder",
        "de": "Aliase-Stammordner",
        "ru": "Корневая папка алиасов",
        "pt": "Pasta raiz de aliases",
        "nl": "Aliassen` root folder",
        "fr": "Le dossier racine des alias",
        "it": "Cartella radice degli alias",
        "es": "Carpeta raíz de alias",
        "pl": "Folder główny aliasów",
        "zh-cn": "别名的根文件夹"
      },
      "type": "meta.folder",
      "dontDelete": true
    },
    "acl": {
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator",
      "object": 1604
    },
    "from": "system.host.smarthome.cli",
    "ts": 1571744117347
  }
}
```

**Comment by Garfonso** [comment]
I think the issue is more complex. The device is not shown, because it is an "info" device (you can enable expert mode, then there will be a button to show info devices and you'll see the device). That means, for some reason the created device is not detected as firealarm but as "info" (which means not properly detected at all) and ignored... 

So my guess is that there is some problem in type-detector (the library used to detect devices) or devices adapter.

**Comment by Garfonso** [comment]
Did some experimentation. The fireAlarm device requires the device to have a role matching `/^sensor(\.alarm)?\.fire$/`. But devices adapter sets the device role to `fireAlarm`. @GermanBluefox should this be handled in devices or in type-detector?

The easiest way to solve this might be do add a new defaultChannelRole field to those state patterns (or better the fireAlarm object?) and set that as role for the device, if encountered.
But the device role seems to be used in devices to display an icon and so on?

floodAlarm probably has the same issue (not tested, yet).

**Comment by GermanBluefox** [comment]
Please test 1.0.7

**Comment by dontobi** [comment]
I have updated to version 1.0.7. Now the smoke detectors are partially displayed (see screenshots). So the smoke detectors are not recognized completely clean.

![image](https://user-images.githubusercontent.com/19261667/124082189-b1c85d00-da4c-11eb-94a5-758807c14894.png)
![image](https://user-images.githubusercontent.com/19261667/124082344-e50aec00-da4c-11eb-89b0-678910138b90.png)

Apart from that, I find it cumbersome that the Homematic devices show up multiple times. This is probably because the devices have a folder structure with folder 0, 1, etc. and the device adapter sees each subfolder with a number as an independent device. Is this the way it is supposed to be? I find this rather annoying. 

However, you have to be careful with this matter, because it is about channels of the Homematic devices. There are socket devices where channel 0 switches a TV and channel 1 switches a lamp. Thus, each channel would be a device.

However, this is different for other devices. For example, the Homematic thermostats, which also has two channels, but both belong to the same device.

![image](https://user-images.githubusercontent.com/19261667/124084630-7e3b0200-da4f-11eb-8456-dcbdcf565e82.png)
![image](https://user-images.githubusercontent.com/19261667/124084736-9448c280-da4f-11eb-94d8-b265ca549b05.png)

**Comment by Garfonso** [comment]
Bluefox fixed the issue about the manually created fireAlarm alias devices. This works for me, now. (i.e. you manually select which state is the fireAlarm and which is indicator for battery and so on). 

As for the homematic issue, there seems to be something else... the role of your .STATE object still is wrong. 

For the duplicate devices (and also the partly correct smoke detectors): try to click on the "i" Symbol, i.e. filter out "info" devices. Those are not real device detections but more a "catch all" thing. It should be much cleaner, if you do not display those. Also, if there are devices missing then (and I think, the smoke detectors will vanish from native devices again) then something is still wrong...

**Comment by dontobi** [comment]
The smoke detectors are now displayed among the native devices and are also recognized by Lovelace. Therefore I will close here.
