### ISSUE TITLE
Unknown types

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.devices#8]
- [ ] Unknown type!camera
- [ ] Unknown type!url
- [ ] Unknown type!gate
- [ ] Unknown type!floodAlarm
- [ ] Unknown type!weatherCurrent

**Comment by derDennis99** [comment]
Unknown type!valve

**Comment by derDennis99** [comment]
Bitte mal die Bugs Fixen!

**Comment by martinschm** [comment]
Still open

**Comment by Ingwaz73** [comment]
These errors still occur. Will these be fixed soon, please?

**Comment by Apollon77** [comment]
it's on the list

**Comment by GermanBluefox** [comment]
Fixed in 1.0.x
