### ISSUE TITLE
Native devices - multiple instances of adapters

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.devices#80]
**Describe the bug**  
During the commissioning of the GEräte adapter I noticed that all devices of the HM-RPC adapter are displayed under "hm.rpc 0". However, some of the devices are running via a second instance of the HM-RPC adapter (see screenshots).

**Expected behavior**  
I think it would be better if under native devices the devices of each instance were shown (hm.rpc 0, hm.rpc 1 etc.) or the subfolders were shown without the instance identifier (hm.rpc instead of hm.rpc 0).

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/19261667/123930348-f3df9900-d98f-11eb-9891-45809b589dce.png)
![image](https://user-images.githubusercontent.com/19261667/123930285-e4f8e680-d98f-11eb-8989-8ad7c1befee0.png)

**Versions:**  
 - Adapter version: 1.0.6
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container

**Additional context**  
Nothing

**Comment by GermanBluefox** [comment]
Please test 1.0.7

**Comment by dontobi** [comment]
Fixed! Thanks.

![image](https://user-images.githubusercontent.com/19261667/124078869-ad9a4080-da48-11eb-8715-fb62e45eaa1d.png)
