### ISSUE TITLE
Native Geräte - Homematic

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.devices#84]
**Describe the bug**  
Unter den nativen Geräten werden mir inzwischen die Geräte von hm-rpc.0 und hm-rpc.1 angezeigt. Jedoch bekomme ich bei vielen Homematic Geräten einzelne Kanäle angezeigt. Siehe folgender Screenshot:
![image](https://user-images.githubusercontent.com/19261667/125196977-29bc3180-e25c-11eb-845a-97c9193074e3.png)
Wenn ich dem Kanal 0 eine Funktion und einen Raum zuordne, werden unter Lovelace einige Entities mit zwei Objekten angezeigt. Siehe folgender Screenshot:
![image](https://user-images.githubusercontent.com/19261667/125197058-87e91480-e25c-11eb-821d-3f925908d9d4.png)
![image](https://user-images.githubusercontent.com/19261667/125197067-92a3a980-e25c-11eb-80e7-bc0502c9aaa7.png)

**Expected behavior**  
Die Geräte sollten lediglich einmal auftauchen und das unabhängig vom Kanal. Bei manchen Homematic Geräten ist der Kanal mit dem Objekt STATE im Kanal 1 zu finden. Andere Geräte wiederum im Kanal 2 oder bei dem Homematic Unterputz Schaltaktor HM-LC-Sw2-FM können es der Kanal 1 und 2 sein.

**Screenshots & Logfiles**  
Siehe oben...

**Versions:**  
 - Adapter version: 1.0.7
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container

**Additional context**  
Ich hänge hier mal von jedem meiner Homematic Geräte ein JSON an. Manche davon habe ich in mehrfacher Ausführung, jedoch wird sicherlich nur ein JSON ausreichen. Die Typenbezeichnung der HM-Geräte stehen hinter dem Bindestrich der verlinkten Datei.
[HM-UnterputzSteckdoese_(1x).zip - HM-LC-Sw1-FM](https://github.com/ioBroker/ioBroker.devices/files/6796997/HM-UnterputzSteckdoese_.1x.zip)
[HM-UnterputzSteckdoese_(2x).zip - HM-LC-Sw2-FM](https://github.com/ioBroker/ioBroker.devices/files/6796998/HM-UnterputzSteckdoese_.2x.zip)
[HM-RollladenAktor.zip - HM-LC-Bl1PBU-FM](https://github.com/ioBroker/ioBroker.devices/files/6796999/HM-RollladenAktor.zip)
[HM-Rauchmelder.zip - HM-Sec-SD-2](https://github.com/ioBroker/ioBroker.devices/files/6797001/HM-Rauchmelder.zip)
[HM-HutschienenAktor.zip - HM-LC-Sw1-DR](https://github.com/ioBroker/ioBroker.devices/files/6797003/HM-HutschienenAktor.zip)
[HM-HutschienenDimAktor.zip - HM-LC-Dim1T-DR](https://github.com/ioBroker/ioBroker.devices/files/6797005/HM-HutschienenDimAktor.zip)
[HM-Tastenfeld.zip - HM-PB-6-WM55](https://github.com/ioBroker/ioBroker.devices/files/6797007/HM-Tastenfeld.zip)
[HM-Taster.zip - HM-RC-2-PBU-FM](https://github.com/ioBroker/ioBroker.devices/files/6797008/HM-Taster.zip)
[HmIP-Fußbodenaktor_6x.zip - HmIP-FAL230-C6](https://github.com/ioBroker/ioBroker.devices/files/6797020/HmIP-Fussbodenaktor_6x.zip)
[HmIP-Fußbodenaktor_10x.zip - HmIP-FAL230-C10](https://github.com/ioBroker/ioBroker.devices/files/6797021/HmIP-Fussbodenaktor_10x.zip)
[HmIP-UnterputzSteckdose.zip - HmIP-FSM](https://github.com/ioBroker/ioBroker.devices/files/6797022/HmIP-UnterputzSteckdose.zip)
[HmIP-Wandthermostat.zip - HmIP-WTH-2](https://github.com/ioBroker/ioBroker.devices/files/6797023/HmIP-Wandthermostat.zip)

**Comment by agross** [comment]
Ich kann zur Validierung bei Interesse JSON für Wandthermostat, Thermostat und Rollladenaktor bereitstellen.

**Comment by dontobi** [comment]
Sind das andere Typen, als die von mir?

**Comment by agross** [comment]
Ich denke schon.

Wandthermostat: HmIP-BWTH
Thermostat: HmIP-eTRV-2
Rollladen: HmIP-BBL
Präsenzmelder: HmIP-SPI

**Comment by GermanBluefox** [comment]
Für die Visualisierung werden nur bestimmte Datenpunkte von einem Gerät genommen, z.B. für Thermostat
Alle Datenpunkte die für das Gerät Thermostat nicht nötig sind, werden noch mal durchgesucht, ob da noch irgendein Gerät zu finden ist. Und genau das sieht man. Man muss manuell die nicht nötige Geräte in lovelace/material deaktivieren

**Comment by dontobi** [comment]
Also verstehe ich das richtig, dass diese Anzeige gewollt ist?
