### ISSUE TITLE
Can't add new devices

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.devices#9]
![18-10-_2019_12-16-39](https://user-images.githubusercontent.com/9552828/67086808-e2496400-f1a1-11e9-87a1-65fb098c3726.png)

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

**Comment by om2804** [comment]
Reinstalling the driver does not solve the problem

**Comment by aokhrimenko** [comment]
Something similar to me. Here a log from console: https://pastebin.com/XN2AUgBL
Possibly it stopped working after upgrade to admin 4. Was working for me yearlier, I have 4 created devices and is able to edit them, but can't create new ones.

Manage devices: 0.3.2
Admin: 4.0.2

```
$ iobroker info
Platform       : linux
os             : linux
Architecture   : x64
CPUs           : 4
Speed          : 1254 MHz
Model          : Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
RAM            : 5.6 GB 
System uptime  : 18d. 23:27:26
Node.js        : v8.16.2
Disk size      : 56.6 GiB
Disk free      : 45.7 GiB
adapters count : 324
NPM            : v6.4.1
```

If you need any input please let me know.

**Comment by julianschill** [comment]
I have the same error in Chrome. It worked in the beginning and the error started probably after installing iobroker.linkeddevices or after changing the language to german. But now the error persists. 

It works in Edge, though. This is a workaround for me now.

**Comment by om2804** [comment]
> 
> 
> I have the same error in Chrome. It worked in the beginning and the error started probably after installing iobroker.linkeddevices or after changing the language to german. But now the error persists.
> 
> It works in Edge, though. This is a workaround for me now.
> 
> EDIT: After deleting the cookies for the admin page in Chrome it works again. I deleted some aliases and folders in the objects tab. Probably something was stored in a cookie, that is not there anymore, e.g. the folder location for the alias.

Yeah. Store cleaning fixed this problem. Clear Local store, Session store, Cookies, Indexed DB, Cache in Firefox
